<?php

namespace App\Libraries;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use RuntimeException;

class Setup
{

    /**
     * 初期データを登録
     * @param $userId
     */
    public function defaultSeeding($userId)
    {
        $this->insertHandPreset($userId);
        $this->insertHandRange($userId);
    }

    /**
     * プリセットの初期データを投入
     * @param $userId
     */
    private function insertHandPreset($userId)
    {
        DB::table('hand_presets')->insert([
            [
                'id' => $userId,
                'name' => 'テストプリセット',
            ],
        ]);
    }

    /**
     * ハンドレンジテーブルをinsert
     * @param $userId
     */
    private function insertHandRange($userId){

        $sbHandInfo =
            [
                ['firstHand' => 'A', 'secondHand' => 'A', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'A', 'secondHand' => 'K', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'A', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'A', 'secondHand' => 'J', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'A', 'secondHand' => 'T', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'A', 'secondHand' => '9', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'A', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'A', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'A', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'A', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'A', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'A', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'A', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

                ['firstHand' => 'K', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
                ['firstHand' => 'K', 'secondHand' => 'K', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'K', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'K', 'secondHand' => 'J', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'K', 'secondHand' => 'T', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'K', 'secondHand' => '9', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'K', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'K', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'K', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'K', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'K', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'K', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'K', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

                ['firstHand' => 'Q', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
                ['firstHand' => 'Q', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
                ['firstHand' => 'Q', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'Q', 'secondHand' => 'J', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'Q', 'secondHand' => 'T', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'Q', 'secondHand' => '9', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'Q', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'Q', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'Q', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'Q', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'Q', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'Q', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'Q', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

                ['firstHand' => 'J', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
                ['firstHand' => 'J', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
                ['firstHand' => 'J', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
                ['firstHand' => 'J', 'secondHand' => 'J', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'J', 'secondHand' => 'T', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'J', 'secondHand' => '9', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'J', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'J', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'J', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'J', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'J', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'J', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'J', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

                ['firstHand' => 'T', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
                ['firstHand' => 'T', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
                ['firstHand' => 'T', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
                ['firstHand' => 'T', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
                ['firstHand' => 'T', 'secondHand' => 'T', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'T', 'secondHand' => '9', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'T', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'T', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'T', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'T', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'T', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'T', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
                ['firstHand' => 'T', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

                ['firstHand' => '9', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '9', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '9', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '9', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '9', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '9', 'secondHand' => '9', 'action' => 'fold', 'suited' => false],
                ['firstHand' => '9', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
                ['firstHand' => '9', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
                ['firstHand' => '9', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
                ['firstHand' => '9', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
                ['firstHand' => '9', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
                ['firstHand' => '9', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
                ['firstHand' => '9', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

                ['firstHand' => '8', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '8', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '8', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '8', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '8', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '8', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '8', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
                ['firstHand' => '8', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
                ['firstHand' => '8', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
                ['firstHand' => '8', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
                ['firstHand' => '8', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
                ['firstHand' => '8', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
                ['firstHand' => '8', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

                ['firstHand' => '7', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '7', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '7', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '7', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '7', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '7', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '7', 'secondHand' => '8', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '7', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
                ['firstHand' => '7', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
                ['firstHand' => '7', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
                ['firstHand' => '7', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
                ['firstHand' => '7', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
                ['firstHand' => '7', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

                ['firstHand' => '6', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '6', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '6', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '6', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '6', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '6', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '6', 'secondHand' => '8', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '6', 'secondHand' => '7', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '6', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
                ['firstHand' => '6', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
                ['firstHand' => '6', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
                ['firstHand' => '6', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
                ['firstHand' => '6', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

                ['firstHand' => '5', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '5', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '5', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '5', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '5', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '5', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '5', 'secondHand' => '8', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '5', 'secondHand' => '7', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '5', 'secondHand' => '6', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '5', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
                ['firstHand' => '5', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
                ['firstHand' => '5', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
                ['firstHand' => '5', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

                ['firstHand' => '4', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '4', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '4', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '4', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '4', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '4', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '4', 'secondHand' => '8', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '4', 'secondHand' => '7', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '4', 'secondHand' => '6', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '4', 'secondHand' => '5', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '4', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
                ['firstHand' => '4', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
                ['firstHand' => '4', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

                ['firstHand' => '3', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '3', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '3', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '3', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '3', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '3', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '3', 'secondHand' => '8', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '3', 'secondHand' => '7', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '3', 'secondHand' => '6', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '3', 'secondHand' => '5', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '3', 'secondHand' => '4', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '3', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
                ['firstHand' => '3', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

                ['firstHand' => '2', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '2', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '2', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '2', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '2', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '2', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '2', 'secondHand' => '8', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '2', 'secondHand' => '7', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '2', 'secondHand' => '6', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '2', 'secondHand' => '5', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '2', 'secondHand' => '4', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '2', 'secondHand' => '3', 'action' => 'fold', 'suited' => true],
                ['firstHand' => '2', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],
            ];
        $SBInsertData =
            [
                'user_id' => $userId,
                'table_type_id' => 1,
                'hand_preset_id' => 1,
                'position_id' => 1,
                'hand_info' => json_encode($sbHandInfo),
                'created_at' => now(),
                'updated_at' => now()
            ];
        DB::table('hand_ranges')->insert($SBInsertData);

        $bbHandInfo = [
            ['firstHand' => 'A', 'secondHand' => 'A', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => 'K', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => 'J', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => 'T', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '9', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => 'K', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'K', 'secondHand' => 'K', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => 'J', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => 'T', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '9', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => 'Q', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'Q', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'Q', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => 'J', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => 'T', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '9', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => 'J', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'J', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'J', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'J', 'secondHand' => 'J', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => 'T', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '9', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => 'T', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'T', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'T', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'T', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'T', 'secondHand' => 'T', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '9', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '9', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '9', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '9', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '9', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '9', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '9', 'secondHand' => '9', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '9', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '9', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '9', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '9', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '9', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '9', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '9', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '8', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '8', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '8', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '8', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '8', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '8', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '8', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '8', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '8', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '8', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '8', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '8', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '8', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '7', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '7', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '7', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '7', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '7', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '7', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '7', 'secondHand' => '8', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '7', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '7', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '7', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '7', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '7', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '7', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '6', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => '8', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => '7', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '6', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '6', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '6', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '6', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '5', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => '8', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => '7', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => '6', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '5', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '5', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '5', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '4', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => '8', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => '7', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => '6', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => '5', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '4', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '4', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '3', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => '8', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => '7', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => '6', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => '5', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => '4', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '3', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '2', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '8', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '7', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '6', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '5', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '4', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '3', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],
        ];
        $BBInsertData =
            [
                'user_id' => $userId,
                'table_type_id' => 1,
                'hand_preset_id' => 1,
                'position_id' => 2,
                'hand_info' => json_encode($bbHandInfo),
                'created_at' => now(),
                'updated_at' => now()
            ];
        DB::table('hand_ranges')->insert($BBInsertData);

        $utgHandInfo = [
            ['firstHand' => 'A', 'secondHand' => 'A', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => 'K', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => 'J', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => 'T', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '9', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => 'K', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'K', 'secondHand' => 'K', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => 'J', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => 'T', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '9', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => 'Q', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'Q', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'Q', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => 'J', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => 'T', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '9', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => 'J', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'J', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'J', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'J', 'secondHand' => 'J', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => 'T', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '9', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => 'T', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'T', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'T', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'T', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'T', 'secondHand' => 'T', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '9', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '9', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '9', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '9', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '9', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '9', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '9', 'secondHand' => '9', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '9', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '9', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '9', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '9', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '9', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '9', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '9', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '8', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '8', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '8', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '8', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '8', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '8', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '8', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '8', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '8', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '8', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '8', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '8', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '8', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '7', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '7', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '7', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '7', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '7', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '7', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '7', 'secondHand' => '8', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '7', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '7', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '7', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '7', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '7', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '7', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '6', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => '8', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => '7', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '6', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '6', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '6', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '6', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '5', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => '8', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => '7', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => '6', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '5', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '5', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '5', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '4', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => '8', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => '7', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => '6', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => '5', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '4', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '4', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '3', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => '8', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => '7', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => '6', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => '5', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => '4', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '3', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '2', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '8', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '7', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '6', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '5', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '4', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '3', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],
        ];
        $UTGInsertData =
            [
                'user_id' => $userId,
                'table_type_id' => 1,
                'hand_preset_id' => 1,
                'position_id' => 3,
                'hand_info' => json_encode($utgHandInfo),
                'created_at' => now(),
                'updated_at' => now()
            ];
        DB::table('hand_ranges')->insert($UTGInsertData);

        $MPHandInfo = [
            ['firstHand' => 'A', 'secondHand' => 'A', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => 'K', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => 'J', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => 'T', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '9', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => 'K', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'K', 'secondHand' => 'K', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => 'J', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => 'T', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '9', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => 'Q', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'Q', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'Q', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => 'J', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => 'T', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '9', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => 'J', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'J', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'J', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'J', 'secondHand' => 'J', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => 'T', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '9', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => 'T', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'T', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'T', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'T', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'T', 'secondHand' => 'T', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '9', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '9', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '9', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '9', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '9', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '9', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '9', 'secondHand' => '9', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '9', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '9', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '9', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '9', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '9', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '9', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '9', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '8', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '8', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '8', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '8', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '8', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '8', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '8', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '8', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '8', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '8', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '8', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '8', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '8', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '7', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '7', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '7', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '7', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '7', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '7', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '7', 'secondHand' => '8', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '7', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '7', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '7', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '7', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '7', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '7', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '6', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => '8', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => '7', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '6', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '6', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '6', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '6', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '5', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => '8', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => '7', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => '6', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '5', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '5', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '5', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '4', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => '8', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => '7', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => '6', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => '5', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '4', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '4', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '3', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => '8', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => '7', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => '6', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => '5', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => '4', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '3', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '2', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '8', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '7', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '6', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '5', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '4', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '3', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],
        ];
        $MPInsertData =
            [
                'user_id' => $userId,
                'table_type_id' => 1,
                'hand_preset_id' => 1,
                'position_id' => 6,
                'hand_info' => json_encode($MPHandInfo),
                'created_at' => now(),
                'updated_at' => now()
            ];
        DB::table('hand_ranges')->insert($MPInsertData);

        $COInsertInfo = [
            ['firstHand' => 'A', 'secondHand' => 'A', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => 'K', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => 'J', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => 'T', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '9', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => 'K', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'K', 'secondHand' => 'K', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => 'J', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => 'T', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '9', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => 'Q', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'Q', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'Q', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => 'J', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => 'T', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '9', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => 'J', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'J', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'J', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'J', 'secondHand' => 'J', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => 'T', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '9', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => 'T', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'T', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'T', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'T', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'T', 'secondHand' => 'T', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '9', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '9', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '9', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '9', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '9', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '9', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '9', 'secondHand' => '9', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '9', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '9', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '9', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '9', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '9', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '9', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '9', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '8', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '8', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '8', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '8', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '8', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '8', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '8', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '8', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '8', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '8', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '8', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '8', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '8', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '7', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '7', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '7', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '7', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '7', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '7', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '7', 'secondHand' => '8', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '7', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '7', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '7', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '7', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '7', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '7', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '6', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => '8', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => '7', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '6', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '6', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '6', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '6', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '5', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => '8', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => '7', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => '6', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '5', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '5', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '5', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '4', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => '8', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => '7', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => '6', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => '5', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '4', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '4', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '3', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => '8', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => '7', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => '6', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => '5', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => '4', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '3', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '2', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '8', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '7', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '6', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '5', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '4', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '3', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],
        ];

        $COInsertData =
            [
                'user_id' => $userId,
                'table_type_id' => 1,
                'hand_preset_id' => 1,
                'position_id' => 9,
                'hand_info' => json_encode($COInsertInfo),
                'created_at' => now(),
                'updated_at' => now()
            ];
        DB::table('hand_ranges')->insert($COInsertData);

        $BTNInsertInfo = [
            ['firstHand' => 'A', 'secondHand' => 'A', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => 'K', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => 'J', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => 'T', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '9', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'A', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => 'K', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'K', 'secondHand' => 'K', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => 'J', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => 'T', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '9', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'K', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => 'Q', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'Q', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'Q', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => 'J', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => 'T', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '9', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'Q', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => 'J', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'J', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'J', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'J', 'secondHand' => 'J', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => 'T', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '9', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'J', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => 'T', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'T', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'T', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'T', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => 'T', 'secondHand' => 'T', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '9', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => 'T', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '9', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '9', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '9', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '9', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '9', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '9', 'secondHand' => '9', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '9', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '9', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '9', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '9', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '9', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '9', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '9', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '8', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '8', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '8', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '8', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '8', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '8', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '8', 'secondHand' => '8', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '8', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '8', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '8', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '8', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '8', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '8', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '7', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '7', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '7', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '7', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '7', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '7', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '7', 'secondHand' => '8', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '7', 'secondHand' => '7', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '7', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '7', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '7', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '7', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '7', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '6', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => '8', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => '7', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '6', 'secondHand' => '6', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '6', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '6', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '6', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '6', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '5', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => '8', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => '7', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => '6', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '5', 'secondHand' => '5', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '5', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '5', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '5', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '4', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => '8', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => '7', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => '6', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => '5', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '4', 'secondHand' => '4', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '4', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '4', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '3', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => '8', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => '7', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => '6', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => '5', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => '4', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '3', 'secondHand' => '3', 'action' => 'fold', 'suited' => false],
            ['firstHand' => '3', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],

            ['firstHand' => '2', 'secondHand' => 'A', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => 'K', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => 'Q', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => 'J', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => 'T', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '9', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '8', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '7', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '6', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '5', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '4', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '3', 'action' => 'fold', 'suited' => true],
            ['firstHand' => '2', 'secondHand' => '2', 'action' => 'fold', 'suited' => false],
        ];

        $BTNInsertData =
            [
                'user_id' => $userId,
                'table_type_id' => 1,
                'hand_preset_id' => 1,
                'position_id' => 10,
                'hand_info' => json_encode($BTNInsertInfo),
                'created_at' => now(),
                'updated_at' => now()
            ];
        DB::table('hand_ranges')->insert($BTNInsertData);
    }
}
